### ISSUE TITLE
Feature: Add Loader

### ISSUE THREAD

**Issue by shubrautt** [hawko666/rick_and_morty#1]
Try `onerror` and `onprogress`
[https://javascript.info/xmlhttprequest](https://javascript.info/xmlhttprequest)

**Comment by hawko666** [comment]
issue has been resolved onerror and onprogress has been added to the code

**Comment by shubrautt** [comment]
**Add Loader** : Build Custom Loader or Use This (https://getbootstrap.com/docs/4.2/components/spinners/)
Create Branch Like This to Add feature -> `Feature/{featureName} `
After Completing Merge Feature Branch into Main

**Comment by hawko666** [comment]
branch has created a loader yet to add.
Will do it tomorrow !!
